INSERT INTO oc_ingredient
    (ingredient_id,name) 
VALUES
    (1,'Mozzarella'),
    (2,'Jambon'),
    (3,'Champignon'),
    (4,'Merguez'),
    (5,'Oignon rouge'),
    (6,'Poivron'),
    (7,'Artichaut'),
    (8,'Tomate'),
    (9,'Poulet'),
    (10,'Oignon'),
    (11,'Olive'),
    (12,'Saumon fumé'),
    (13,'Viande haché'),
    (14,'Sauce curry'),
    (15,'Creme fraiche'),
    (16,'Poire'),
    (17,'Roquefort'),
    (18,'Miel'),
    (19,'Noix'),
    (20,'Sauce tomate'),
    (21,'Anchois'),
    (22,'Câpre'),
    (23,'Oeuf');